version: '3'

services:
    web:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        volumes:
          - ./www:/var/www
        ports:
          - 9080:80
        links:
          - php
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
          -  ./php.ini:/usr/local/etc/php/php.ini
          -  ./html:/var/www/
    mysql:
        image: mysql:5.7
        environment:
          -  MYSQL_ROOT_PASSWORD=root
          -  MYSQL_DATABASE=test
          -  MYSQL_USER=test
          -  MYSQL_PASSWORD=test
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
          -  ./db/mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          -  PMA_ARBITRARY=1
          -  PMA_HOST=mysql
          -  PMA_USER=root
          -  PMA_PASSWORD=root
        links:
          -  mysql
        ports:
          -  4040:80
        volumes:
          -  ./phpmyadmin/sessions:/sessions
